= Packer setup for OpenNMS

This repository allows to create base box images with OpenNMS and Grafana.
It is mostly used with Vagrant but can be extented to create Amazon EC2, Docker, Google Compute Engine, OpenStack or VMware images.

The default configuration is build to generate a Vagrant Base Box image.

The system is build with a disk size of 20 GB and 2GB RAM.
Other parameters for RAM and CPU depend on the configuration in the packer template JSON file.

== Requirements and environments

The cookbook is build based on the following requirements:

 * Internet access to download ISO images and packages
 * link:https://www.virtualbox.org/wiki/Downloads[latest VirtualBox]
 * link:http://www.packer.io/downloads.html[packer]

== Usage

- Download or clone the repository from GitHub, there is a ZIP and tar.gz file also available in 'releases'.
----
git clone https://github.com/opennms-forge/packer-opennms.git
----

Change into the 'packer-opennms/ubuntu-lts' directory and build the base box based on Ubuntu:

----
cd packer-opennms/ubuntu-lts
packer build -var opennms_release=stable -only=virtualbox-iso template.json
----

Change into the 'packer-opennms/centos-7' directory and build the base box based on CentOS:

----
cd packer-opennms/centos-7
packer build -var opennms_release=stable -only=virtualbox-iso template.json
----

With `-only=virtualbox-iso` only the VirtualBox based image will be created.
The 'template.json' file contains the PXE boot, kickstart-files and builds the system from scratch.

== Contributing

1. Fork the repository on Github
2. Create a named feature branch (i.e. `add-new-recipe`)
6. Submit a Pull Request

== License and Authors

Author:: Ronny Trommer <ronny@opennms.org>
Copyright (c) 2014 The OpenNMS Group, Inc.
License:: GPLv3+
